language: python
python:
  - "2.7"
install:
  - pip -r requirements.txt
  - pip install .
script: make
after_success:
  coveralls
notifications:
  slack:
    rooms:
      - sys:yeTvjm0bw1tX6MBWrfkVL5RG#travis
