language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install .
script: nosetests --with-coverage --cover-package=sanji
after_success:
  coveralls
notifications:
  slack:
    rooms:
      - sys:yeTvjm0bw1tX6MBWrfkVL5RG#travis
